available_locales:
  en: "en"
  ja: "ja"
  vi: "vi"

gravatar:
  url: "https://secure.gravatar.com/avatar"
  emails: "https://gravatar.com/emails"
  size: 80
  list_size: 50

static_pages:
  home:
    rails_tutorial_link: "http://www.railstutorial.org/"

  help:
    help_link: "http://www.railstutorial.org/help"
    book_link: "http://www.railstutorial.org/book"

user:
  email:
    regex: '\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z'
    max_length: 255
  name:
    max_length: 50

pagy:
  items: 10

password:
  minimum: 6
